import type { Guide } from "./types";

export const GUIDES: Guide[] = [
  {
    slug: "twelve-shots",
    title: "The 12 shots that catch 80% of bad units",
    dek: "You do not need a camera bag. You need a sequence and a flash.",
    minutes: 8,
    body: [
      "Open houses are designed so you remember the light and forget the floor. The listing already spent money to hide the same twelve places. Your job is to photograph those places in order, with the flash on, before the broker turns you toward the skyline.",
      "Shot one: the claimed bedroom from the doorway, full room, every wall. You are proving whether a window to the exterior exists. If the listing says two bedrooms and you can only find one windowed room, you have already found the flex. Do not argue in the hallway. Take the picture.",
      "Shot two: the window itself, sash or slider fully open, with a tape or a phone in the clear opening. Egress is a measurement, not a feeling. A hopper five feet up is not a way out of a fire. A garden-level well that is grated and padlocked is not a way out either.",
      "Shot three: under the sink, cabinet doors open, flash on. Supply lines, shutoffs, the trap, the cabinet floor. Cardboard that has gone wavy is evidence. A bulge in a braided line is a Tuesday flood.",
      "Shot four: the dishwasher toe-kick, from the floor. Listing photos are taken standing up so this is cropped. A dark line on the kick plate is not ‘character.’ It is a leak that has already happened.",
      "Shot five: the hall slope. Put a marble or a bottle on the floor and record both directions. Area rugs in listing photos exist to kill this shot. Brokers will laugh. Let them. Slope toward a wet wall is a story you want in writing.",
      "Shot six: every bathroom outlet within reach of water. You are looking for TEST and RESET. Two-prong plates next to a tub are not charming. They are the electric that was never opened during the ‘update.’",
      "Shot seven: the actual heating and cooling appliance, nameplate in the frame. ‘Central air’ that is a portable with a hose is a walk in Los Angeles and Austin. ‘Central heat’ that is a radiator is not a lie, but it is not what a first-time buyer thinks it means in Chicago.",
      "Shot eight: ceiling patches in raking light. A rectangle of different texture over the bed is a leak from above. Ask whose. Ask whether it returned. Photograph the floor directly underneath.",
      "Shot nine: the second exit. Fire escape, back stair, porch, or the other door of a guest house. Photograph the whole run. Painted-shut sashes and locked yard gates fail this silently.",
      "Shot ten: grade and downspouts, or in a city flat, the rear extension floor and the drain outside it. Water against the building is damp, slab movement, or a wet London garden flat.",
      "Shot eleven: the partition. If a wall looks new, photograph where it meets the original ceiling. Hollow-core and cornice cutoffs are how illegal bedrooms get born.",
      "Shot twelve: the smell and the noise, which are not photos. Ten seconds of video with audio in the quietest claimed bedroom, and a note on the slider for gut. You will not remember the bus at 6 a.m. from a Saturday noon showing.",
      "If the broker is rushing you, you do not skip randomly. You skip décor. You keep one, two, three, four, seven, and nine. ShowingKit will shorten the remaining list live. The brief is only as good as the shots you actually took. Advisory only — this is not an inspection.",
    ],
  },
  {
    slug: "listing-language",
    title: "How listing language hides problems",
    dek: "The copy is not description. It is a set of tokens. Read them as risk.",
    minutes: 7,
    body: [
      "A listing is an advertisement with a floor plan. The photographer is paid to stand in the one corner that makes the room look legal. The copywriter is paid to use words that have been A/B tested against your hope. You are not rude for treating the language as a map of what they would rather you not photograph.",
      "‘Cozy’ means small, and often dark. Measure wall to wall. Photograph the window from the wall where a bed would go. If the noon sun does not reach the floor, January will not either.",
      "‘Flex’ is the most expensive adjective in rental copy. It means a room that is not a bedroom and is being sold as one. In New York it is frequently windowless. In Austin it is a porch. In London it is a box room. Count exterior windows, not bed icons on a PDF.",
      "‘Garden level’ and ‘garden flat’ mean below grade. The light is a well. The damp is gravity. The noise is the sidewalk. None of that is a reason to walk by itself — it is a reason to photograph skirting, wells, and the rear door threshold.",
      "‘Recently updated’ and ‘recently refreshed’ are concealment tokens. Paint is cheap. Plumbing is not. The question is what was opened: the stack, the electric, the roof, the boiler. If the answer is ‘the cabinets,’ you still need the toe-kick shot and the GFCI shot.",
      "‘New kitchen in a pre-war’ is a specific risk. New boxes on old shutoffs. Dishwashers on original lines. You will not see this from standing height. Get on the floor.",
      "‘Utilities included’ without a cap is not generosity in a building with electric heat or portable AC. Ask for last winter’s bill anyway. If they cannot produce one, write that down. The brief will treat the missing bill as a number, not a vibe.",
      "‘Parking included’ is a distance. Photograph the stall, walk it with a timer, look at the lighting. A lot four blocks away is not parking. A tandem slope in Los Angeles is not parking you will use.",
      "‘Central air’ and ‘central heat’ are claims about equipment. Photograph the equipment. A portable in the closet is not central. A radiator is heat, and it is honest, but it is not what the phrase means to someone coming from a 2019 condo.",
      "‘Must see’ and ‘won’t last’ are clocks, not facts. They are useful to you only as a reminder that your brief has to exist the same afternoon. The texts ShowingKit writes are for that window: a clarifying question, a concession, a deadline. Send them while you still remember the stain.",
      "Read the listing once as a renter. Read it again as a prosecutor. Circle the tokens. Those circles become the shot list. Advisory only.",
    ],
  },
  {
    slug: "flex-bedroom",
    title: "What ‘flex bedroom’ usually means",
    dek: "A curtain is not a wall. A wall is not a window. A window is not egress.",
    minutes: 7,
    body: [
      "Flex is a marketing word for a room that failed the bedroom test and was sent back to the copywriter. The floor plan will show a bed. The photos will show a living room from an angle that hides the missing window. The broker will say ‘a lot of people use it as a bedroom.’ A lot of people also overpay.",
      "In New York, flex usually means a living room with a partition, or a windowless inner room. The partition is often hollow-core and stops short of the original plaster. The inner room may have borrowed light through glass block. Neither is a legal bedroom under the housing-code heuristic we use. We label it a heuristic because we are not your lawyer and we are not DOB.",
      "In Los Angeles, flex is often a converted garage or a guest-house alcove. One door, a high window, portable AC. The listing will still say 2 bed. You will sleep in a box if the kitchenette goes.",
      "In London, flex is the box room: a small room with a sash that does not open, or a room on a light well. Agents will say ‘perfect for a nursery.’ Nurseries also need air.",
      "The test is boring, which is why it works. Stand in the doorway. Is there a window to the exterior or a legal court? Can you open it, and is the clear opening big enough to climb through? Can you get from that room to a second exit without going through the kitchen if the kitchen is on fire? If any answer is no, it is not a bedroom. It may still be a useful office. Pay office rent for it.",
      "Unpermitted partitions have tells. The cornice is cut. Outlets live on one side. The wall sounds empty when you knock. The ceiling texture changes on one side of the new line. Photograph the joint. If you buy the place, that wall may have to come down, and the ‘three bed’ price comes down with it.",
      "Brokers will offer a free-standing wardrobe as a wall. They will offer a bookcase. They will say the last tenant slept there for years. None of that writes a second means of egress onto the certificate.",
      "What you do with the finding depends on your dealbreakers. If legal bedroom is a hard walk, you walk — same afternoon, no apology. If it is a negotiate, the brief should carry a dollar range for the missing room, not a speech. In most cities that range is a four-figure annual miss on rent, or a five-figure miss on price, because the next buyer will count windows too.",
      "ShowingKit’s city playbooks encode this as a heuristic. We stamp it on the brief. We do not certify the unit. If you need a legal determination, hire the person whose stamp a bank will take. Our job is to stop you from calling a closet a bedroom because the listing did.",
    ],
  },
  {
    slug: "same-afternoon",
    title: "How to negotiate the same afternoon",
    dek: "The brief is a page. The texts are three. The window is hours, not days.",
    minutes: 8,
    body: [
      "Saturday is a conveyor. You will see two or three places. Each broker wants a same-day application because the next open house is already on the calendar. If you go home to ‘think about it,’ you either overpay tonight or lose it to someone who applied on the sidewalk. The third option is a written, specific ask before dinner.",
      "Do the showing with a timer. Do not perform delight. Photograph the failure points. On the sidewalk, run the evidence. The agent needs four things from you: the visit photos, a caption on each, anything the broker said out loud, and your gut sliders. That is enough for a brief. Notes-only works, and we will label it weaker.",
      "Read the verdict as a decision, not a mood. WALK means a dealbreaker failed or the unit is misrepresented in a way you will not be able to live with. Do not send a concession text on a walk — send nothing, or a short decline. NEGOTIATE means the unit is livable with a price or a repair. OFFER means the claims mostly survived contact with the floor.",
      "The dollar figures are ranges because we are not appraisers. A dishwasher leak in a $2,850 Bushwick two-bed is not a $37.50 problem. It is a few hundred off the monthly, or a repair in writing before you sign, or both. Portable AC sold as central in Los Angeles is larger. A missing legal bedroom is larger still. If the range feels wide, that is honesty.",
      "Three texts, in order. First, a clarifying question that proves you were in the room: ‘The toe-kick under the dishwasher is stained and the cabinet floor is wet — was this disclosed, and has the line been replaced?’ Specific, calm, not a lawyer. Second, the concession: a number or a repair, tied to the photo. Third, the clock: you have another listing this afternoon, you can sign today if the number moves. Do not bluff a listing you do not have. The demo data includes other listings because Maya actually has them.",
      "Tone. Brokers are not villains and they are not your friends. They are paid to close. You are paid, in the form of rent, to not be the person who discovers the leak in month two. Short sentences. Nouns. No ‘per my last.’ No statute cites unless you are actually a lawyer, which this tool assumes you are not.",
      "If you are going with a partner, do not negotiate by committee in the hallway. One of you runs the shot list. One of you talks. The brief is the conversation you have on the stoop, not in front of the listing agent.",
      "Send before you sit down on the train. The field brief is one page so you can do that. Print it if you want a paper in your pocket; the print stylesheet is built for that. Advisory only. If the number is life-changing, get a human with a license to read the same photos.",
    ],
  },
  {
    slug: "what-it-is-not",
    title: "What ShowingKit is not",
    dek: "Not a licensed inspection. Not a lawyer. Not a reason to skip either.",
    minutes: 6,
    body: [
      "ShowingKit is a field notebook with opinions. It tells you what to photograph, then it writes down what the photographs did to the listing’s claims. That is the whole product. It is useful because open houses are theater and because first-time renters and buyers are not contractors. It is dangerous if you treat the stamp as a certificate.",
      "We are not a licensed home inspector. We do not carry errors-and-omissions insurance for your purchase. We do not get on the roof. We do not test for asbestos, lead, or mould in a lab. A spongey subfloor in the brief is a note to hire the person who will open the floor. It is not a finding you can hand to a seller as gospel.",
      "We are not a lawyer and we are not your city’s housing department. When we say a windowless room is not a bedroom in New York, that is a heuristic based on how those rooms are commonly treated. It is labeled as a heuristic on every city page and every brief. If you need a determination that survives a complaint or a mortgage, pay for that determination.",
      "We are not an appraisal. The dollar ranges are order-of-magnitude negotiation brackets tied to the kind of defect, the rent, and the city. They are not a discounted cash flow. They exist so you do not ask for $40 off a $3,000 apartment with a leak, and so you do not walk away from a $200 problem that a plumber can actually fix.",
      "We are not a substitute for your own eyes on a weekday night. A Saturday noon showing will not teach you the bus. The noise slider is a prompt to come back, not a measurement.",
      "This demo stores your data in the browser. It is not a vault. Do not upload documents you would not leave on a café table. Partner sharing in this build is a mock link, not encryption.",
      "What we are: a same-day system for people who have twenty minutes in a unit and a tendency to leave with vibes. Use it to walk, to ask, or to offer. Then, if the number is large enough, hire the inspector and the lawyer. The brief even says so at the bottom. Read that line. It is the only part we will not let you customize.",
    ],
  },
];
