import type { Minutes, Shot, Template } from "./types";

type ShotDraft = Omit<Shot, "id" | "checked" | "skipped" | "order">;

function materialize(drafts: ShotDraft[], minutes: Minutes): Shot[] {
  const totalPriority = drafts.reduce((s, d) => s + d.priority, 0) || 1;
  return drafts.map((d, i) => ({
    ...d,
    id: `shot-tpl-${i + 1}`,
    checked: false,
    order: i + 1,
    minutes: Math.max(1, Math.round((d.priority / totalPriority) * minutes)),
  }));
}

const NYC_RENTER: ShotDraft[] = [
  {
    room: "Entry",
    title: "Door, lockset, intercom test",
    why: "Buzzer theater. Test in and out.",
    failCondition: "Intercom dead, or lock is a single cylinder you cannot control.",
    askOutLoud: "Does the buzzer work from this unit, and who has keys to the lobby door?",
    minutes: 1,
    captionHint: "Entry door",
    priority: 8,
  },
  {
    room: "Bedroom 1",
    title: "Full room from the door, then the window opening",
    why: "NYC: no exterior window, not a bedroom.",
    failCondition: "No window to the exterior or court, or opening too small to climb.",
    askOutLoud: "Is this a legal bedroom, and can I see it on the certificate?",
    minutes: 2,
    captionHint: "Bedroom window",
    priority: 10,
  },
  {
    room: "Bedroom 2 / flex",
    title: "Prove the second bedroom exists",
    why: "Flex is the expensive adjective.",
    failCondition: "Windowless, borrowed light, or a curtain wall.",
    askOutLoud: "When you say two bed, do you mean two legal sleeping rooms?",
    minutes: 2,
    captionHint: "Flex room",
    priority: 10,
  },
  {
    room: "Kitchen",
    title: "Toe-kick and under-sink, flash on",
    why: "Listing crops this. Leaks live here.",
    failCondition: "Stain, swollen MDF, wet cardboard, supply bulge.",
    askOutLoud: "Has the dishwasher ever leaked, and were the lines replaced?",
    minutes: 3,
    captionHint: "Under sink",
    priority: 10,
  },
  {
    room: "Hall",
    title: "Marble test both ways",
    why: "Slope toward a wet wall is a leak story.",
    failCondition: "Marble runs with intent; door will not latch.",
    askOutLoud: "Any history of leaks from above?",
    minutes: 1,
    captionHint: "Hall slope",
    priority: 7,
  },
  {
    room: "Bath",
    title: "GFCI and caulk line",
    why: "Water + old electric, and caulk as costume.",
    failCondition: "No GFCI near water; mildew under fresh caulk.",
    askOutLoud: "When was the bath last opened, not just recaulked?",
    minutes: 2,
    captionHint: "Bath GFCI",
    priority: 8,
  },
  {
    room: "Egress",
    title: "Fire escape or second exit, full run",
    why: "Painted shut is not an exit.",
    failCondition: "Blocked, rusted, no second path from the rear room.",
    askOutLoud: "Can we open this window fully?",
    minutes: 2,
    captionHint: "Fire escape",
    priority: 9,
  },
  {
    room: "Ceilings",
    title: "Raking light on patches",
    why: "Upstairs dishwashers donate water.",
    failCondition: "Texture rectangle over a bed or table.",
    askOutLoud: "Whose leak was that, and did it return?",
    minutes: 1,
    captionHint: "Ceiling patch",
    priority: 6,
  },
];

const BUYER_BUNGALOW: ShotDraft[] = [
  {
    room: "Exterior",
    title: "Grade and downspouts, all corners",
    why: "Water against the slab is the expensive story.",
    failCondition: "Soil slopes in; downspout dumps at the foundation.",
    askOutLoud: "Any foundation work, and can I see invoices?",
    minutes: 2,
    captionHint: "Grade",
    priority: 10,
  },
  {
    room: "HVAC",
    title: "Condenser, air handler, nameplate",
    why: "Tonnage vs additions. Portable is not central.",
    failCondition: "No condenser, or portable hose in a window.",
    askOutLoud: "Age, last service, did it hold last August?",
    minutes: 2,
    captionHint: "AC nameplate",
    priority: 10,
  },
  {
    room: "Slab",
    title: "Brick line, door latches, marble in the hall",
    why: "Movement shows before the seller says piers.",
    failCondition: "Cracked brick, doors that catch, marble runs.",
    askOutLoud: "Has the house been pierced or leveled?",
    minutes: 2,
    captionHint: "Slab crack",
    priority: 9,
  },
  {
    room: "Bedrooms",
    title: "Egress window in each sleeping room",
    why: "Enclosed garages steal the second exit.",
    failCondition: "High hopper only, or no opening.",
    askOutLoud: "Which rooms are permitted sleeping rooms?",
    minutes: 2,
    captionHint: "Bedroom egress",
    priority: 9,
  },
  {
    room: "Attic",
    title: "Hatch: decking, bath fans, foam",
    why: "Fans dumping into the attic become mould.",
    failCondition: "Wet sheathing, bath fans unvented.",
    askOutLoud: "May I put a camera in the hatch?",
    minutes: 2,
    captionHint: "Attic",
    priority: 7,
  },
  {
    room: "Water heater",
    title: "Pan, drain, strap or stand",
    why: "Attic heaters fail onto kitchens.",
    failCondition: "No pan, no drain, rust at the base.",
    askOutLoud: "Age, and has it leaked?",
    minutes: 1,
    captionHint: "Water heater",
    priority: 7,
  },
  {
    room: "Kitchen",
    title: "Under-sink and the addition seam",
    why: "The new kitchen was a porch.",
    failCondition: "Floor transition, supply bulge, different joist direction.",
    askOutLoud: "Was this an addition, and was HVAC upsized?",
    minutes: 2,
    captionHint: "Under sink",
    priority: 8,
  },
];

const GARDEN_SKEPTIC: ShotDraft[] = [
  {
    room: "Light well",
    title: "Window well, grate, drain",
    why: "Garden level lives or dies on the well.",
    failCondition: "Standing water, grate padlocked, rusted lintel.",
    askOutLoud: "How often does the well hold water?",
    minutes: 2,
    captionHint: "Window well",
    priority: 10,
  },
  {
    room: "Skirting",
    title: "External wall, flash, behind furniture",
    why: "Paint over damp. Tide marks at the board.",
    failCondition: "Bubbling paint, brown line, cellar smell.",
    askOutLoud: "Any damp treatment, and can I see the report?",
    minutes: 2,
    captionHint: "Skirting damp",
    priority: 10,
  },
  {
    room: "Rear door",
    title: "Threshold and outside drain",
    why: "Below-grade extensions hold water at the door.",
    failCondition: "Soft floor, rusted threshold, blocked gully.",
    askOutLoud: "Has water come in at this door?",
    minutes: 2,
    captionHint: "Rear threshold",
    priority: 9,
  },
  {
    room: "Sash",
    title: "Condensation, operation, gap at the meeting rail",
    why: "Single glaze + garden humidity.",
    failCondition: "Painted shut, heavy condensation, card through the gap.",
    askOutLoud: "Are these original sashes, and is there secondary glazing?",
    minutes: 2,
    captionHint: "Sash",
    priority: 9,
  },
  {
    room: "Bedroom",
    title: "Egress from the sleeping room",
    why: "Well windows are not always a way out.",
    failCondition: "Cannot open, cannot climb, grate locked.",
    askOutLoud: "If the stair is blocked, how does someone leave this room?",
    minutes: 2,
    captionHint: "Egress",
    priority: 10,
  },
  {
    room: "Smell",
    title: "Wardrobe pulled, 10-second video",
    why: "Mould behind furniture on the cold wall.",
    failCondition: "Sweet or cellar smell, black on the wall behind.",
    askOutLoud: "May I look behind the wardrobe?",
    minutes: 1,
    captionHint: "Behind furniture",
    priority: 8,
  },
];

export const STARTER_TEMPLATES: Template[] = [
  {
    id: "tpl-nyc-20",
    name: "20-min renter NYC",
    description: "Legal bedroom, toe-kick, slope, GFCI, fire escape.",
    city: "nyc",
    minutes: 20,
    shots: materialize(NYC_RENTER, 20),
  },
  {
    id: "tpl-buyer-15",
    name: "15-min buyer bungalow",
    description: "Grade, HVAC nameplate, slab, egress, attic hatch.",
    minutes: 15,
    shots: materialize(BUYER_BUNGALOW, 15),
  },
  {
    id: "tpl-garden",
    name: "Garden-level skepticism",
    description: "Wells, skirting, rear threshold, sashes, the cold wall.",
    minutes: 20,
    shots: materialize(GARDEN_SKEPTIC, 20),
  },
];

export const PRESET_DEALBREAKERS = [
  { id: "db-legal-bed", label: "Legal bedroom", severity: "hard" as const },
  { id: "db-wd", label: "W/D in unit", severity: "negotiate" as const },
  { id: "db-parking", label: "Parking on site", severity: "negotiate" as const },
  { id: "db-carpet", label: "No carpet", severity: "note" as const },
  { id: "db-ground", label: "Ground floor", severity: "note" as const },
  { id: "db-pets", label: "Pets allowed", severity: "hard" as const },
  { id: "db-quiet", label: "Quiet at night", severity: "negotiate" as const },
  { id: "db-ac", label: "Central air actually central", severity: "hard" as const },
];
